import { useState, useRef, useEffect } from 'react';
import { Icon, type IconName } from './Icon';

const EMOJI_CATEGORIES = [
  {
    name: 'People',
    icon: 'user',
    emojis: [
      { char: '😀', name: 'grinning face' },
      { char: '😃', name: 'grinning face with big eyes' },
      { char: '😄', name: 'grinning face with smiling eyes' },
      { char: '😁', name: 'beaming face with smiling eyes' },
      { char: '😆', name: 'grinning squinting face' },
      { char: '😅', name: 'grinning face with sweat' },
      { char: '🤣', name: 'rolling on the floor laughing' },
      { char: '😂', name: 'face with tears of joy' },
      { char: '🙂', name: 'slightly smiling face' },
      { char: '😉', name: 'winking face' },
      { char: '😊', name: 'smiling face with smiling eyes' },
      { char: '😇', name: 'smiling face with halo' },
      { char: '🥰', name: 'smiling face with hearts' },
      { char: '😍', name: 'smiling face with heart-eyes' },
      { char: '🤩', name: 'star-struck' },
      { char: '😘', name: 'face blowing a kiss' },
      { char: '😗', name: 'kissing face' },
      { char: '😚', name: 'kissing face with closed eyes' },
      { char: '😙', name: 'kissing face with smiling eyes' },
      { char: '😋', name: 'face savoring food' },
      { char: '😛', name: 'face with tongue' },
      { char: '😜', name: 'winking face with tongue' },
      { char: '🤪', name: 'zany face' },
      { char: '😝', name: 'squinting face with tongue' },
      { char: '🤑', name: 'money-mouth face' },
      { char: '🤗', name: 'hugging face' },
      { char: '🤭', name: 'face with hand over mouth' },
      { char: '🤫', name: 'shushing face' },
      { char: '🤔', name: 'thinking face' },
      { char: '🤐', name: 'zipper-mouth face' },
      { char: '🤨', name: 'face with raised eyebrow' },
      { char: '😐', name: 'neutral face' },
      { char: '😑', name: 'expressionless face' },
      { char: '😶', name: 'face without mouth' },
      { char: '😏', name: 'smirking face' },
      { char: '😒', name: 'unamused face' },
      { char: '🙄', name: 'face with rolling eyes' },
      { char: '😬', name: 'grimacing face' },
      { char: '🤥', name: 'lying face' },
      { char: '😌', name: 'relieved face' },
      { char: '😔', name: 'pensive face' },
      { char: '😪', name: 'sleepy face' },
      { char: '🤤', name: 'drooling face' },
      { char: '😴', name: 'sleeping face' },
      { char: '😷', name: 'face with medical mask' },
      { char: '🤒', name: 'face with thermometer' },
      { char: '🤕', name: 'face with head-bandage' },
      { char: '🤢', name: 'nauseated face' },
      { char: '🤮', name: 'face vomiting' },
      { char: '🤧', name: 'sneezing face' },
      { char: '🥵', name: 'hot face' },
      { char: '🥶', name: 'cold face' },
      { char: '🥴', name: 'woozy face' },
      { char: '😵', name: 'knocked-out face' },
      { char: '🤯', name: 'exploding head' },
      { char: '🤠', name: 'cowboy hat face' },
      { char: '🥳', name: 'partying face' },
      { char: '😎', name: 'smiling face with sunglasses' },
      { char: '🤓', name: 'nerd face' },
      { char: '🧐', name: 'monocle face' },
      { char: '😕', name: 'confused face' },
      { char: '😟', name: 'worried face' },
      { char: '🙁', name: 'slightly frowning face' },
      { char: '☹️', name: 'frowning face' },
      { char: '😮', name: 'face with open mouth' },
      { char: '😯', name: 'hushed face' },
      { char: '😲', name: 'astonished face' },
      { char: '😳', name: 'flushed face' },
      { char: '😱', name: 'face screaming in fear' },
      { char: '😨', name: 'fearful face' },
      { char: '😰', name: 'anxious face with sweat' },
      { char: '😢', name: 'crying face' },
      { char: '😭', name: 'loudly crying face' },
      { char: '😤', name: 'steam from nose' },
      { char: '😠', name: 'angry face' },
      { char: '😡', name: 'pouting face' },
      { char: '🤬', name: 'face with symbols on mouth' },
      { char: '😷', name: 'face with medical mask' },
      { char: '🤒', name: 'face with thermometer' },
      { char: '🤕', name: 'face with head-bandage' },
      { char: '🤢', name: 'nauseated face' },
      { char: '🤮', name: 'face vomiting' },
      { char: '🤧', name: 'sneezing face' },
    ],
  },
  {
    name: 'Nature',
    icon: 'tree-pine',
    emojis: [
      { char: '🐶', name: 'dog face' },
      { char: '🐱', name: 'cat face' },
      { char: '🐭', name: 'mouse face' },
      { char: '🐹', name: 'hamster face' },
      { char: '🐰', name: 'rabbit face' },
      { char: '🦊', name: 'fox face' },
      { char: '🐻', name: 'bear face' },
      { char: '🐼', name: 'panda face' },
      { char: '🐻‍❄️', name: 'polar bear face' },
      { char: '🐨', name: 'koala face' },
      { char: '🐯', name: 'tiger face' },
      { char: '🦁', name: 'lion face' },
      { char: '🐮', name: 'cow face' },
      { char: '🐷', name: 'pig face' },
      { char: '🐽', name: 'pig nose' },
      { char: '🐸', name: 'frog face' },
      { char: '🐵', name: 'monkey face' },
      { char: '🙈', name: 'see-no-evil monkey' },
      { char: '🙉', name: 'hear-no-evil monkey' },
      { char: '🙊', name: 'speak-no-evil monkey' },
      { char: '🐒', name: 'monkey' },
      { char: '🐔', name: 'chicken' },
      { char: '🐧', name: 'penguin' },
      { char: '🐦', name: 'bird' },
      { char: '🐤', name: 'baby chick' },
      { char: '🐣', name: 'hatching chick' },
      { char: '🐥', name: 'front-facing baby chick' },
      { char: '🐺', name: 'wolf face' },
      { char: '🦁', name: 'lion face' },
      { char: '🐮', name: 'cow face' },
      { char: '🐷', name: 'pig face' },
      { char: '🐽', name: 'pig nose' },
      { char: '🐸', name: 'frog face' },
      { char: '🐙', name: 'octopus' },
      { char: '🦑', name: 'squid' },
      { char: '🦐', name: 'shrimp' },
      { char: '🦞', name: 'lobster' },
      { char: '🦟', name: 'mosquito' },
      { char: '🦋', name: 'butterfly' },
      { char: '🌸', name: 'cherry blossom' },
      { char: '🌷', name: 'tulip' },
      { char: '🌹', name: 'rose' },
      { char: '🌻', name: 'sunflower' },
      { char: '🌿', name: 'herb' },
      { char: '🍀', name: 'four leaf clover' },
      { char: '🌲', name: 'evergreen tree' },
      { char: '🌳', name: 'deciduous tree' },
      { char: '🌴', name: 'palm tree' },
      { char: '🌵', name: 'cactus' },
      { char: '🌾', name: 'sheaf of rice' },
      { char: '🌱', name: 'seedling' },
      { char: '🌲', name: 'evergreen tree' },
      { char: '🌳', name: 'deciduous tree' },
      { char: '🌴', name: 'palm tree' },
      { char: '🌵', name: 'cactus' },
      { char: '🌾', name: 'sheaf of rice' },
      { char: '🌱', name: 'seedling' },
      { char: '🍄', name: 'mushroom' },
      { char: '🐚', name: 'spiral shell' },
      { char: '🌕', name: 'full moon' },
      { char: '🌖', name: 'waning gibbous moon' },
      { char: '🌗', name: 'last quarter moon' },
      { char: '🌘', name: 'waning crescent moon' },
      { char: '🌑', name: 'new moon' },
      { char: '🌒', name: 'waxing crescent moon' },
      { char: '🌓', name: 'first quarter moon' },
      { char: '🌔', name: 'waxing gibbous moon' },
      { char: '🌙', name: 'crescent moon' },
      { char: '🌚', name: 'new moon face' },
      { char: '🌛', name: 'first quarter moon face' },
      { char: '🌜', name: 'last quarter moon face' },
      { char: '🌝', name: 'full moon face' },
      { char: '🌞', name: 'sun with face' },
      { char: '⭐', name: 'star' },
      { char: '🌟', name: 'glowing star' },
      { char: '🌠', name: 'shooting star' },
      { char: '☁️', name: 'cloud' },
      { char: '⛈️', name: 'cloud with lightning and rain' },
      { char: '🌈', name: 'rainbow' },
      { char: '⚡', name: 'high voltage' },
      { char: '❄️', name: 'snowflake' },
      { char: '☃️', name: 'snowman' },
      { char: '⛄', name: 'snowman without snow' },
      { char: '🌬️', name: 'wind face' },
      { char: '🌊', name: 'water wave' },
    ],
  },
  {
    name: 'Food',
    icon: 'utensils',
    emojis: [
      { char: '🍏', name: 'green apple' },
      { char: '🍎', name: 'red apple' },
      { char: '🍐', name: 'pear' },
      { char: '🍊', name: 'tangerine' },
      { char: '🍋', name: 'lemon' },
      { char: '🍌', name: 'banana' },
      { char: '🍉', name: 'watermelon' },
      { char: '🍇', name: 'grapes' },
      { char: '🍓', name: 'strawberry' },
      { char: '🫐', name: 'blueberries' },
      { char: '🍈', name: 'melon' },
      { char: '🍒', name: 'cherries' },
      { char: '🍑', name: 'peach' },
      { char: '🥭', name: 'mango' },
      { char: '🍍', name: 'pineapple' },
      { char: '🥭', name: 'mango' },
      { char: '🥝', name: 'kiwi fruit' },
      { char: '🍅', name: 'tomato' },
      { char: '🥥', name: 'coconut' },
      { char: '🥑', name: 'avocado' },
      { char: '🥦', name: 'broccoli' },
      { char: '🥒', name: 'cucumber' },
      { char: '🌽', name: 'ear of corn' },
      { char: '🥕', name: 'carrot' },
      { char: '🥔', name: 'potato' },
      { char: '🍠', name: 'roasted sweet potato' },
      { char: '🥜', name: 'peanuts' },
      { char: '🍯', name: 'honey pot' },
      { char: '🍞', name: 'bread' },
      { char: '🥐', name: 'croissant' },
      { char: '🥖', name: 'baguette bread' },
      { char: '🥨', name: 'pretzel' },
      { char: '🥯', name: 'bagel' },
      { char: '🥞', name: 'pancakes' },
      { char: '🧇', name: 'waffle' },
      { char: '🧀', name: 'cheese wedge' },
      { char: '🍖', name: 'meat on bone' },
      { char: '🍗', name: 'poultry leg' },
      { char: '🥩', name: 'cut of meat' },
      { char: '🥓', name: 'bacon' },
      { char: '🍔', name: 'hamburger' },
      { char: '🍟', name: 'french fries' },
      { char: '🍕', name: 'pizza' },
      { char: '🌭', name: 'hot dog' },
      { char: '🥪', name: 'sandwich' },
      { char: '🌮', name: 'taco' },
      { char: '🌯', name: 'burrito' },
      { char: '🥙', name: 'stuffed flatbread' },
      { char: '🧆', name: 'falafel' },
      { char: '🥚', name: 'egg' },
      { char: '🍳', name: 'cooking' },
      { char: '🥘', name: 'shallow pan of food' },
      { char: '🍲', name: 'pot of food' },
      { char: '🥣', name: 'bowl with spoon' },
      { char: '🥗', name: 'green salad' },
      { char: '🍿', name: 'popcorn' },
      { char: '🧈', name: 'butter' },
      { char: '🧂', name: 'salt' },
      { char: '🥫', name: 'canned food' },
      { char: '🍱', name: 'bento box' },
      { char: '🍘', name: 'rice cracker' },
      { char: '🍙', name: 'rice ball' },
      { char: '🍚', name: 'cooked rice' },
      { char: '🍛', name: 'curry rice' },
      { char: '🍜', name: 'steaming bowl' },
      { char: '🍝', name: 'spaghetti' },
      { char: '🍠', name: 'roasted sweet potato' },
      { char: '🍢', name: 'oden' },
      { char: '🍣', name: 'sushi' },
      { char: '🍤', name: 'fried shrimp' },
      { char: '🍥', name: 'fish cake with swirl' },
      { char: '🥮', name: 'moon cake' },
      { char: '🍡', name: 'dango' },
      { char: '🥟', name: 'dumpling' },
      { char: '🥠', name: 'fortune cookie' },
      { char: '🥡', name: 'takeout box' },
      { char: '🦀', name: 'crab' },
      { char: '🦞', name: 'lobster' },
      { char: '🦐', name: 'shrimp' },
      { char: '🦑', name: 'squid' },
      { char: '🦪', name: 'oyster' },
      { char: '🍦', name: 'soft ice cream' },
      { char: '🍧', name: 'shaved ice' },
      { char: '🍨', name: 'ice cream' },
      { char: '🍩', name: 'doughnut' },
      { char: '🍪', name: 'cookie' },
      { char: '🎂', name: 'birthday cake' },
      { char: '🍰', name: 'shortcake' },
      { char: '🧁', name: 'cupcake' },
      { char: '🥧', name: 'pie' },
      { char: '🍫', name: 'chocolate bar' },
      { char: '🍬', name: 'candy' },
      { char: '🍭', name: 'lollipop' },
      { char: '🍮', name: 'custard' },
      { char: '🍯', name: 'honey pot' },
      { char: '🍼', name: 'baby bottle' },
      { char: '🥛', name: 'glass of milk' },
      { char: '☕', name: 'hot beverage' },
      { char: '🫖', name: 'teapot' },
      { char: '🍵', name: 'tea cup without handle' },
      { char: '🍶', name: 'sake' },
      { char: '🍾', name: 'bottle with popping cork' },
      { char: '🍷', name: 'wine glass' },
      { char: '🍸', name: 'cocktail glass' },
      { char: '🍹', name: 'tropical drink' },
      { char: '🍺', name: 'beer mug' },
      { char: '🍻', name: 'clinking beer mugs' },
      { char: '🥂', name: 'clinking glasses' },
      { char: '🥃', name: 'tumbler glass' },
      { char: '🥤', name: 'cup with straw' },
      { char: '🧃', name: 'beverage box' },
      { char: '🧉', name: 'mate' },
      { char: '🧊', name: 'ice cube' },
    ],
  },
  {
    name: 'Activities',
    icon: 'gamepad-2',
    emojis: [
      { char: '⚽', name: 'soccer ball' },
      { char: '🏀', name: 'basketball' },
      { char: '🏈', name: 'american football' },
      { char: '⚾', name: 'baseball' },
      { char: '🥎', name: 'softball' },
      { char: '🎾', name: 'tennis' },
      { char: '🏐', name: 'volleyball' },
      { char: '🏉', name: 'rugby football' },
      { char: '🎱', name: 'pool 8 ball' },
      { char: '🏓', name: 'ping pong' },
      { char: '🏸', name: 'badminton' },
      { char: '🏏', name: 'cricket' },
      { char: '🏑', name: 'field hockey' },
      { char: '🏒', name: 'ice hockey' },
      { char: '🥍', name: 'lacrosse' },
      { char: '🏹', name: 'archery' },
      { char: '🎣', name: 'fishing pole' },
      { char: '🤿', name: 'diving mask' },
      { char: '🎽', name: 'running shirt' },
      { char: '🎿', name: 'skis' },
      { char: '🛷', name: 'sled' },
      { char: '🥌', name: 'curling stone' },
      { char: '🎯', name: 'bullseye' },
      { char: '🎮', name: 'video game' },
      { char: '🕹️', name: 'joystick' },
      { char: '🎰', name: 'slot machine' },
      { char: '🎲', name: 'game die' },
      { char: '🧩', name: 'puzzle piece' },
      { char: '🧸', name: 'teddy bear' },
      { char: '🪅', name: 'piñata' },
      { char: '🪆', name: 'nesting dolls' },
      { char: '♠️', name: 'spade suit' },
      { char: '♥️', name: 'heart suit' },
      { char: '♦️', name: 'diamond suit' },
      { char: '♣️', name: 'club suit' },
      { char: '♟️', name: 'chess pawn' },
      { char: '🃏', name: 'joker' },
      { char: '🀄', name: 'mahjong red dragon' },
      { char: '🎴', name: 'flower playing cards' },
      { char: '🎭', name: 'performing arts' },
      { char: '🖼️', name: 'framed picture' },
      { char: '🎨', name: 'artist palette' },
      { char: '🧵', name: 'thread' },
      { char: '🪡', name: 'sewing needle' },
      { char: '🧶', name: 'yarn' },
      { char: '🪢', name: 'knot' },
    ],
  },
  {
    name: 'Travel',
    icon: 'plane',
    emojis: [
      { char: '🚗', name: 'automobile' },
      { char: '🚕', name: 'taxi' },
      { char: '🚙', name: 'sport utility vehicle' },
      { char: '🚌', name: 'bus' },
      { char: '🚎', name: 'trolleybus' },
      { char: '🏎️', name: 'racing car' },
      { char: '🚓', name: 'police car' },
      { char: '🚑', name: 'ambulance' },
      { char: '🚒', name: 'fire engine' },
      { char: '🚐', name: 'minibus' },
      { char: '🛻', name: 'pickup truck' },
      { char: '🚚', name: 'delivery truck' },
      { char: '🚛', name: 'articulated lorry' },
      { char: '🚜', name: 'tractor' },
      { char: '🛴', name: 'kick scooter' },
      { char: '🚲', name: 'bicycle' },
      { char: '🛵', name: 'motor scooter' },
      { char: '🏍️', name: 'motorcycle' },
      { char: '🛺', name: 'auto rickshaw' },
      { char: '🚨', name: 'police car light' },
      { char: '🚔', name: 'oncoming police car' },
      { char: '🚍', name: 'oncoming bus' },
      { char: '🚘', name: 'oncoming automobile' },
      { char: '🚖', name: 'oncoming taxi' },
      { char: '🚡', name: 'aerial tramway' },
      { char: '🚠', name: 'mountain cableway' },
      { char: '🚟', name: 'suspension railway' },
      { char: '🚃', name: 'railway car' },
      { char: '🚋', name: 'tram car' },
      { char: '🚞', name: 'mountain railway' },
      { char: '🚝', name: 'monorail' },
      { char: '🚄', name: 'high-speed train' },
      { char: '🚅', name: 'bullet train' },
      { char: '🚈', name: 'light rail' },
      { char: '🚂', name: 'steam locomotive' },
      { char: '🚆', name: 'train' },
      { char: '🚇', name: 'metro' },
      { char: '🚊', name: 'tram' },
      { char: '🚉', name: 'station' },
      { char: '✈️', name: 'airplane' },
      { char: '🛫', name: 'airplane departure' },
      { char: '🛬', name: 'airplane arrival' },
      { char: '🛩️', name: 'small airplane' },
      { char: '🛸', name: 'flying saucer' },
      { char: '🚁', name: 'helicopter' },
      { char: '🚀', name: 'rocket' },
      { char: '🛰️', name: 'satellite' },
      { char: '🛸', name: 'flying saucer' },
      { char: '🌌', name: 'milky way' },
      { char: '🪐', name: 'ringed planet' },
      { char: '🌑', name: 'new moon' },
      { char: '🌒', name: 'waxing crescent moon' },
      { char: '🌓', name: 'first quarter moon' },
      { char: '🌔', name: 'waxing gibbous moon' },
      { char: '🌕', name: 'full moon' },
      { char: '🌖', name: 'waning gibbous moon' },
      { char: '🌗', name: 'last quarter moon' },
      { char: '🌘', name: 'waning crescent moon' },
      { char: '🌙', name: 'crescent moon' },
      { char: '🌚', name: 'new moon face' },
      { char: '🌛', name: 'first quarter moon face' },
      { char: '🌜', name: 'last quarter moon face' },
      { char: '🌝', name: 'full moon face' },
      { char: '🌞', name: 'sun with face' },
      { char: '🪐', name: 'ringed planet' },
      { char: '⭐', name: 'star' },
      { char: '🌟', name: 'glowing star' },
      { char: '🌠', name: 'shooting star' },
      { char: '🌌', name: 'milky way' },
      { char: '☁️', name: 'cloud' },
      { char: '⛅', name: 'sun behind cloud' },
      { char: '🌤️', name: 'sun behind small cloud' },
      { char: '🌥️', name: 'sun behind large cloud' },
      { char: '🌦️', name: 'sun behind rain cloud' },
      { char: '🌧️', name: 'cloud with rain' },
      { char: '⛈️', name: 'cloud with lightning and rain' },
      { char: '🌩️', name: 'cloud with lightning' },
      { char: '🌨️', name: 'cloud with snow' },
      { char: '🌬️', name: 'wind face' },
      { char: '🌫️', name: 'fog' },
      { char: '🌈', name: 'rainbow' },
      { char: '☀️', name: 'sun' },
      { char: '🌤️', name: 'sun behind small cloud' },
      { char: '⛅', name: 'sun behind cloud' },
      { char: '🌥️', name: 'sun behind large cloud' },
      { char: '🌦️', name: 'sun behind rain cloud' },
      { char: '🌧️', name: 'cloud with rain' },
      { char: '⛈️', name: 'cloud with lightning and rain' },
      { char: '🌩️', name: 'cloud with lightning' },
      { char: '🌨️', name: 'cloud with snow' },
      { char: '🌬️', name: 'wind face' },
      { char: '🌫️', name: 'fog' },
    ],
  },
  {
    name: 'Objects',
    icon: 'package',
    emojis: [
      { char: '📱', name: 'mobile phone' },
      { char: '📲', name: 'mobile phone with arrow' },
      { char: '☎️', name: 'telephone' },
      { char: '📞', name: 'telephone receiver' },
      { char: '📟', name: 'pager' },
      { char: '📠', name: 'fax machine' },
      { char: '🔋', name: 'battery' },
      { char: '🔌', name: 'electric plug' },
      { char: '💻', name: 'laptop' },
      { char: '🖥️', name: 'desktop computer' },
      { char: '🖨️', name: 'printer' },
      { char: '⌨️', name: 'keyboard' },
      { char: '🖱️', name: 'computer mouse' },
      { char: '🖲️', name: 'trackball' },
      { char: '💽', name: 'computer disk' },
      { char: '💾', name: 'floppy disk' },
      { char: '💿', name: 'optical disk' },
      { char: '📀', name: 'dvd' },
      { char: '🧮', name: 'abacus' },
      { char: '🎥', name: 'movie camera' },
      { char: '🎬', name: 'clapper board' },
      { char: '📹', name: 'video camera' },
      { char: '📷', name: 'camera' },
      { char: '📸', name: 'camera with flash' },
      { char: '📺', name: 'television' },
      { char: '📻', name: 'radio' },
      { char: '🎙️', name: 'studio microphone' },
      { char: '🎚️', name: 'level slider' },
      { char: '🎛️', name: 'control knobs' },
      { char: '⏱️', name: 'stopwatch' },
      { char: '⏲️', name: 'timer clock' },
      { char: '⏰', name: 'alarm clock' },
      { char: '🕰️', name: 'mantelpiece clock' },
      { char: '⏳', name: 'hourglass not done' },
      { char: '⌛', name: 'hourglass done' },
      { char: '📍', name: 'round pushpin' },
      { char: '📌', name: 'pushpin' },
      { char: '🧭', name: 'compass' },
      { char: '🗺️', name: 'world map' },
      { char: '🧱', name: 'brick' },
      { char: '🧲', name: 'magnet' },
      { char: '🪨', name: 'rock' },
      { char: '🪵', name: 'wood' },
      { char: '🔪', name: 'kitchen knife' },
      { char: '🪚', name: 'carpentry saw' },
      { char: '🔧', name: 'wrench' },
      { char: '🪛', name: 'screwdriver' },
      { char: '🔨', name: 'hammer' },
      { char: '🪛', name: 'screwdriver' },
      { char: '🔩', name: 'nut and bolt' },
      { char: '⚙️', name: 'gear' },
      { char: '🗜️', name: 'clamp' },
      { char: '⚖️', name: 'balance scale' },
      { char: '🦺', name: 'safety vest' },
      { char: '🔗', name: 'chains' },
      { char: '⛓️', name: 'chains' },
      { char: '🧰', name: 'toolbox' },
      { char: '🧲', name: 'magnet' },
      { char: '🪜', name: 'ladder' },
      { char: '🧱', name: 'brick' },
      { char: '🧲', name: 'magnet' },
      { char: '🪨', name: 'rock' },
      { char: '🪵', name: 'wood' },
    ],
  },
  {
    name: 'Symbols',
    icon: 'heart',
    emojis: [
      { char: '❤️', name: 'red heart' },
      { char: '🧡', name: 'orange heart' },
      { char: '💛', name: 'yellow heart' },
      { char: '💚', name: 'green heart' },
      { char: '💙', name: 'blue heart' },
      { char: '💜', name: 'purple heart' },
      { char: '🤎', name: 'brown heart' },
      { char: '🖤', name: 'black heart' },
      { char: '🤍', name: 'white heart' },
      { char: '💔', name: 'broken heart' },
      { char: '❣️', name: 'heart exclamation' },
      { char: '💕', name: 'two hearts' },
      { char: '💞', name: 'revolving hearts' },
      { char: '💓', name: 'beating heart' },
      { char: '💗', name: 'growing heart' },
      { char: '💖', name: 'sparkling heart' },
      { char: '💘', name: 'heart with arrow' },
      { char: '💝', name: 'heart with ribbon' },
      { char: '💟', name: 'heart decoration' },
      { char: '☮️', name: 'peace symbol' },
      { char: '✝️', name: 'latin cross' },
      { char: '☪️', name: 'star and crescent' },
      { char: '🕉️', name: 'om' },
      { char: '☸️', name: 'wheel of dharma' },
      { char: '✡️', name: 'star of david' },
      { char: '☯️', name: 'yin yang' },
      { char: '☦️', name: 'orthodox cross' },
      { char: '🛐', name: 'place of worship' },
      { char: '⛎', name: 'ophiuchus' },
      { char: '♈', name: 'aries' },
      { char: '♉', name: 'taurus' },
      { char: '♊', name: 'gemini' },
      { char: '♋', name: 'cancer' },
      { char: '♌', name: 'leo' },
      { char: '♍', name: 'virgo' },
      { char: '♎', name: 'libra' },
      { char: '♏', name: 'scorpio' },
      { char: '♐', name: 'sagittarius' },
      { char: '♑', name: 'capricorn' },
      { char: '♒', name: 'aquarius' },
      { char: '♓', name: 'pisces' },
      { char: '🔯', name: 'six pointed star with middle dot' },
      { char: '⚛️', name: 'atom symbol' },
      { char: '🕎', name: 'menorah' },
      { char: '🔯', name: 'six pointed star with middle dot' },
      { char: '♻️', name: 'recycling symbol' },
      { char: '⚜️', name: 'fleur-de-lis' },
      { char: '🔱', name: 'trident emblem' },
      { char: '📛', name: 'name badge' },
      { char: '🔰', name: 'Japanese symbol for beginner' },
      { char: '⭕', name: 'hollow red circle' },
      { char: '✅', name: 'check mark button' },
      { char: '☑️', name: 'check box with check' },
      { char: '✔️', name: 'check mark' },
      { char: '✖️', name: 'cross mark' },
      { char: '❌', name: 'cross mark' },
      { char: '❎', name: 'cross mark button' },
      { char: '➕', name: 'plus' },
      { char: '➖', name: 'minus' },
      { char: '➗', name: 'divide' },
      { char: '➰', name: 'curly loop' },
      { char: '➿', name: 'double curly loop' },
      { char: '〽️', name: 'part alternation mark' },
      { char: '✳️', name: 'eight-spoked asterisk' },
      { char: '✴️', name: 'eight-pointed star' },
      { char: '❇️', name: 'sparkle' },
      { char: '‼️', name: 'double exclamation mark' },
      { char: '⁉️', name: 'exclamation question mark' },
      { char: '❓', name: 'question mark' },
      { char: '❔', name: 'white question mark' },
      { char: '❕', name: 'white exclamation mark' },
      { char: '❗', name: 'exclamation mark' },
      { char: '〰️', name: 'wavy dash' },
      { char: '💯', name: 'hundred points' },
      { char: '💢', name: 'anger symbol' },
      { char: '♨️', name: 'hot springs' },
      { char: '🚸', name: 'children crossing' },
      { char: '🚫', name: 'prohibited' },
      { char: '🚳', name: 'no bicycles' },
      { char: '🚭', name: 'no smoking' },
      { char: '🚯', name: 'no littering' },
      { char: '🚱', name: 'non-potable water' },
      { char: '🚷', name: 'no pedestrians' },
      { char: '📵', name: 'no mobile phones' },
      { char: '🔞', name: 'no one under eighteen' },
      { char: '☢️', name: 'radioactive' },
      { char: '☣️', name: 'biohazard' },
      { char: '⬆️', name: 'up arrow' },
      { char: '⬇️', name: 'down arrow' },
      { char: '➡️', name: 'right arrow' },
      { char: '⬅️', name: 'left arrow' },
      { char: '↗️', name: 'up-right arrow' },
      { char: '↙️', name: 'down-left arrow' },
      { char: '↘️', name: 'down-right arrow' },
      { char: '↖️', name: 'up-left arrow' },
      { char: '↩️', name: 'right arrow curving left' },
      { char: '↪️', name: 'left arrow curving right' },
      { char: '⤴️', name: 'right arrow curving up' },
      { char: '⤵️', name: 'right arrow curving down' },
      { char: '🔃', name: 'clockwise vertical arrows' },
      { char: '🔄', name: 'counterclockwise arrows button' },
      { char: '🔙', name: 'BACK arrow' },
      { char: '🔚', name: 'END arrow' },
      { char: '🔛', name: 'ON! arrow' },
      { char: '🔜', name: 'SOON arrow' },
      { char: '🔝', name: 'TOP arrow' },
      { char: '🛐', name: 'place of worship' },
      { char: '⚛️', name: 'atom symbol' },
      { char: '🕉️', name: 'om' },
      { char: '✡️', name: 'star of david' },
      { char: '☸️', name: 'wheel of dharma' },
      { char: '☯️', name: 'yin yang' },
      { char: '☦️', name: 'orthodox cross' },
      { char: '🛐', name: 'place of worship' },
      { char: '⛎', name: 'ophiuchus' },
      { char: '♈', name: 'aries' },
      { char: '♉', name: 'taurus' },
      { char: '♊', name: 'gemini' },
      { char: '♋', name: 'cancer' },
      { char: '♌', name: 'leo' },
      { char: '♍', name: 'virgo' },
      { char: '♎', name: 'libra' },
      { char: '♏', name: 'scorpio' },
      { char: '♐', name: 'sagittarius' },
      { char: '♑', name: 'capricorn' },
      { char: '♒', name: 'aquarius' },
      { char: '♓', name: 'pisces' },
    ],
  },
  {
    name: 'Flags',
    icon: 'flag',
    emojis: [
      { char: '🏳️', name: 'white flag' },
      { char: '🏴', name: 'black flag' },
      { char: '🏴‍☠️', name: 'pirate flag' },
      { char: '🏁', name: 'chequered flag' },
      { char: '🚩', name: 'triangular flag' },
      { char: '🏳️‍🌈', name: 'rainbow flag' },
      { char: '🏳️‍⚧️', name: 'transgender flag' },
      { char: '🇦🇨', name: 'Ascension Island' },
      { char: '🇦🇩', name: 'Andorra' },
      { char: '🇦🇪', name: 'United Arab Emirates' },
      { char: '🇦🇫', name: 'Afghanistan' },
      { char: '🇦🇬', name: 'Antigua & Barbuda' },
      { char: '🇦🇮', name: 'Anguilla' },
      { char: '🇦🇱', name: 'Albania' },
      { char: '🇦🇲', name: 'Armenia' },
      { char: '🇦🇴', name: 'Angola' },
      { char: '🇦🇶', name: 'Antarctica' },
      { char: '🇦🇷', name: 'Argentina' },
      { char: '🇦🇸', name: 'American Samoa' },
      { char: '🇦🇹', name: 'Austria' },
      { char: '🇦🇺', name: 'Australia' },
      { char: '🇦🇼', name: 'Aruba' },
      { char: '🇦🇽', name: 'Åland Islands' },
      { char: '🇦🇿', name: 'Azerbaijan' },
      { char: '🇧🇦', name: 'Bosnia & Herzegovina' },
      { char: '🇧🇧', name: 'Barbados' },
      { char: '🇧🇩', name: 'Bangladesh' },
      { char: '🇧🇪', name: 'Belgium' },
      { char: '🇧🇫', name: 'Burkina Faso' },
      { char: '🇧🇬', name: 'Bulgaria' },
      { char: '🇧🇭', name: 'Bahrain' },
      { char: '🇧🇮', name: 'Burundi' },
      { char: '🇧🇯', name: 'Benin' },
      { char: '🇧🇱', name: 'St. Barthélemy' },
      { char: '🇧🇲', name: 'Bermuda' },
      { char: '🇧🇳', name: 'Brunei' },
      { char: '🇧🇴', name: 'Bolivia' },
      { char: '🇧🇶', name: 'Caribbean Netherlands' },
      { char: '🇧🇷', name: 'Brazil' },
      { char: '🇧🇸', name: 'Bahamas' },
      { char: '🇧🇹', name: 'Bhutan' },
      { char: '🇧🇻', name: 'Bouvet Island' },
      { char: '🇧🇼', name: 'Botswana' },
      { char: '🇧🇾', name: 'Belarus' },
      { char: '🇧🇿', name: 'Belize' },
      { char: '🇨🇦', name: 'Canada' },
      { char: '🇨🇨', name: 'Cocos Islands' },
      { char: '🇨🇩', name: 'Congo - Kinshasa' },
      { char: '🇨🇫', name: 'Central African Republic' },
      { char: '🇨🇬', name: 'Congo - Brazzaville' },
      { char: '🇨🇭', name: 'Switzerland' },
      { char: '🇨🇮', name: 'Côte d\'Ivoire' },
      { char: '🇨🇰', name: 'Cook Islands' },
      { char: '🇨🇱', name: 'Chile' },
      { char: '🇨🇲', name: 'Cameroon' },
      { char: '🇨🇳', name: 'China' },
      { char: '🇨🇴', name: 'Colombia' },
      { char: '🇨🇵', name: 'Clipperton Island' },
      { char: '🇨🇷', name: 'Costa Rica' },
      { char: '🇨🇺', name: 'Cuba' },
      { char: '🇨🇻', name: 'Cape Verde' },
      { char: '🇨🇼', name: 'Curaçao' },
      { char: '🇨🇽', name: 'Christmas Island' },
      { char: '🇨🇾', name: 'Cyprus' },
      { char: '🇨🇿', name: 'Czechia' },
      { char: '🇩🇪', name: 'Germany' },
      { char: '🇩🇬', name: 'Diego Garcia' },
      { char: '🇩🇯', name: 'Djibouti' },
      { char: '🇩🇰', name: 'Denmark' },
      { char: '🇩🇲', name: 'Dominica' },
      { char: '🇩🇴', name: 'Dominican Republic' },
      { char: '🇩🇿', name: 'Algeria' },
      { char: '🇪🇨', name: 'Ecuador' },
      { char: '🇪🇪', name: 'Estonia' },
      { char: '🇪🇬', name: 'Egypt' },
      { char: '🇪🇭', name: 'Western Sahara' },
      { char: '🇪🇷', name: 'Eritrea' },
      { char: '🇪🇸', name: 'Spain' },
      { char: '🇪🇹', name: 'Ethiopia' },
      { char: '🇪🇺', name: 'European Union' },
      { char: '🇫🇮', name: 'Finland' },
      { char: '🇫🇯', name: 'Fiji' },
      { char: '🇫🇰', name: 'Falkland Islands' },
      { char: '🇫🇲', name: 'Micronesia' },
      { char: '🇫🇴', name: 'Faroe Islands' },
      { char: '🇫🇷', name: 'France' },
      { char: '🇬🇦', name: 'Gabon' },
      { char: '🇬🇧', name: 'United Kingdom' },
      { char: '🇬🇩', name: 'Grenada' },
      { char: '🇬🇪', name: 'Georgia' },
      { char: '🇬🇫', name: 'French Guiana' },
      { char: '🇬🇬', name: 'Guernsey' },
      { char: '🇬🇭', name: 'Ghana' },
      { char: '🇬🇮', name: 'Gibraltar' },
      { char: '🇬🇱', name: 'Greenland' },
      { char: '🇬🇲', name: 'Gambia' },
      { char: '🇬🇳', name: 'Guinea' },
      { char: '🇬🇵', name: 'Guadeloupe' },
      { char: '🇬🇶', name: 'Equatorial Guinea' },
      { char: '🇬🇷', name: 'Greece' },
      { char: '🇬🇸', name: 'South Georgia & South Sandwich Islands' },
      { char: '🇬🇹', name: 'Guatemala' },
      { char: '🇬🇺', name: 'Guam' },
      { char: '🇬🇼', name: 'Guinea-Bissau' },
      { char: '🇬🇾', name: 'Guyana' },
      { char: '🇭🇰', name: 'Hong Kong SAR China' },
      { char: '🇭🇲', name: 'Heard & McDonald Islands' },
      { char: '🇭🇳', name: 'Honduras' },
      { char: '🇭🇷', name: 'Croatia' },
      { char: '🇭🇹', name: 'Haiti' },
      { char: '🇭🇺', name: 'Hungary' },
      { char: '🇮🇨', name: 'Canary Islands' },
      { char: '🇮🇩', name: 'Indonesia' },
      { char: '🇮🇪', name: 'Ireland' },
      { char: '🇮🇱', name: 'Israel' },
      { char: '🇮🇲', name: 'Isle of Man' },
      { char: '🇮🇳', name: 'India' },
      { char: '🇮🇴', name: 'British Indian Ocean Territory' },
      { char: '🇮🇶', name: 'Iraq' },
      { char: '🇮🇷', name: 'Iran' },
      { char: '🇮🇸', name: 'Iceland' },
      { char: '🇮🇹', name: 'Italy' },
      { char: '🇯🇪', name: 'Jersey' },
      { char: '🇯🇲', name: 'Jamaica' },
      { char: '🇯🇴', name: 'Jordan' },
      { char: '🇯🇵', name: 'Japan' },
      { char: '🇰🇪', name: 'Kenya' },
      { char: '🇰🇬', name: 'Kyrgyzstan' },
      { char: '🇰🇭', name: 'Cambodia' },
      { char: '🇰🇮', name: 'Kiribati' },
      { char: '🇰🇲', name: 'Comoros' },
      { char: '🇰🇳', name: 'St. Kitts & Nevis' },
      { char: '🇰🇵', name: 'North Korea' },
      { char: '🇰🇷', name: 'South Korea' },
      { char: '🇰🇼', name: 'Kuwait' },
      { char: '🇰🇾', name: 'Cayman Islands' },
      { char: '🇰🇿', name: 'Kazakhstan' },
      { char: '🇱🇦', name: 'Laos' },
      { char: '🇱🇧', name: 'Lebanon' },
      { char: '🇱🇨', name: 'St. Lucia' },
      { char: '🇱🇮', name: 'Liechtenstein' },
      { char: '🇱🇰', name: 'Sri Lanka' },
      { char: '🇱🇷', name: 'Liberia' },
      { char: '🇱🇸', name: 'Lesotho' },
      { char: '🇱🇹', name: 'Lithuania' },
      { char: '🇱🇺', name: 'Luxembourg' },
      { char: '🇱🇻', name: 'Latvia' },
      { char: '🇱🇾', name: 'Libya' },
      { char: '🇲🇦', name: 'Morocco' },
      { char: '🇲🇨', name: 'Monaco' },
      { char: '🇲🇩', name: 'Moldova' },
      { char: '🇲🇪', name: 'Montenegro' },
      { char: '🇲🇫', name: 'St. Martin' },
      { char: '🇲🇬', name: 'Madagascar' },
      { char: '🇲🇭', name: 'Marshall Islands' },
      { char: '🇲🇰', name: 'North Macedonia' },
      { char: '🇲🇱', name: 'Mali' },
      { char: '🇲🇲', name: 'Myanmar (Burma)' },
      { char: '🇲🇳', name: 'Mongolia' },
      { char: '🇲🇴', name: 'Macao SAR China' },
      { char: '🇲🇵', name: 'Northern Mariana Islands' },
      { char: '🇲🇶', name: 'Martinique' },
      { char: '🇲🇷', name: 'Mauritania' },
      { char: '🇲🇸', name: 'Montserrat' },
      { char: '🇲🇹', name: 'Malta' },
      { char: '🇲🇺', name: 'Mauritius' },
      { char: '🇲🇻', name: 'Maldives' },
      { char: '🇲🇼', name: 'Malawi' },
      { char: '🇲🇽', name: 'Mexico' },
      { char: '🇲🇾', name: 'Malaysia' },
      { char: '🇲🇿', name: 'Mozambique' },
      { char: '🇳🇦', name: 'Namibia' },
      { char: '🇳🇨', name: 'New Caledonia' },
      { char: '🇳🇪', name: 'Niger' },
      { char: '🇳🇫', name: 'Norfolk Island' },
      { char: '🇳🇬', name: 'Nigeria' },
      { char: '🇳🇮', name: 'Nicaragua' },
      { char: '🇳🇱', name: 'Netherlands' },
      { char: '🇳🇴', name: 'Norway' },
      { char: '🇳🇵', name: 'Nepal' },
      { char: '🇳🇷', name: 'Nauru' },
      { char: '🇳🇺', name: 'Niue' },
      { char: '🇳🇿', name: 'New Zealand' },
      { char: '🇴🇲', name: 'Oman' },
      { char: '🇵🇦', name: 'Panama' },
      { char: '🇵🇪', name: 'Peru' },
      { char: '🇵🇫', name: 'French Polynesia' },
      { char: '🇵🇬', name: 'Papua New Guinea' },
      { char: '🇵🇭', name: 'Philippines' },
      { char: '🇵🇰', name: 'Pakistan' },
      { char: '🇵🇱', name: 'Poland' },
      { char: '🇵🇲', name: 'St. Pierre & Miquelon' },
      { char: '🇵🇳', name: 'Pitcairn Islands' },
      { char: '🇵🇷', name: 'Puerto Rico' },
      { char: '🇵🇸', name: 'Palestinian Territories' },
      { char: '🇵🇹', name: 'Portugal' },
      { char: '🇵🇼', name: 'Palau' },
      { char: '🇵🇾', name: 'Paraguay' },
      { char: '🇶🇦', name: 'Qatar' },
      { char: '🇷🇪', name: 'Réunion' },
      { char: '🇷🇴', name: 'Romania' },
      { char: '🇷🇸', name: 'Serbia' },
      { char: '🇷🇺', name: 'Russia' },
      { char: '🇷🇼', name: 'Rwanda' },
      { char: '🇸🇦', name: 'Saudi Arabia' },
      { char: '🇸🇧', name: 'Solomon Islands' },
      { char: '🇸🇨', name: 'Seychelles' },
      { char: '🇸🇩', name: 'Sudan' },
      { char: '🇸🇪', name: 'Sweden' },
      { char: '🇸🇬', name: 'Singapore' },
      { char: '🇸🇭', name: 'St. Helena' },
      { char: '🇸🇮', name: 'Slovenia' },
      { char: '🇸🇯', name: 'Svalbard & Jan Mayen' },
      { char: '🇸🇰', name: 'Slovakia' },
      { char: '🇸🇱', name: 'Sierra Leone' },
      { char: '🇸🇲', name: 'San Marino' },
      { char: '🇸🇳', name: 'Senegal' },
      { char: '🇸🇴', name: 'Somalia' },
      { char: '🇸🇷', name: 'Suriname' },
      { char: '🇸🇸', name: 'South Sudan' },
      { char: '🇸🇹', name: 'São Tomé & Príncipe' },
      { char: '🇸🇻', name: 'El Salvador' },
      { char: '🇸🇽', name: 'Sint Maarten' },
      { char: '🇸🇾', name: 'Syria' },
      { char: '🇸🇿', name: 'Eswatini' },
      { char: '🇹🇦', name: 'Tristan da Cunha' },
      { char: '🇹🇨', name: 'Turks & Caicos Islands' },
      { char: '🇹🇩', name: 'Chad' },
      { char: '🇹🇫', name: 'French Southern Territories' },
      { char: '🇹🇬', name: 'Togo' },
      { char: '🇹🇭', name: 'Thailand' },
      { char: '🇹🇯', name: 'Tajikistan' },
      { char: '🇹🇰', name: 'Tokelau' },
      { char: '🇹🇱', name: 'Timor-Leste' },
      { char: '🇹🇲', name: 'Turkmenistan' },
      { char: '🇹🇳', name: 'Tunisia' },
      { char: '🇹🇴', name: 'Tonga' },
      { char: '🇹🇷', name: 'Turkey' },
      { char: '🇹🇹', name: 'Trinidad & Tobago' },
      { char: '🇹🇻', name: 'Tuvalu' },
      { char: '🇹🇼', name: 'Taiwan' },
      { char: '🇹🇿', name: 'Tanzania' },
      { char: '🇺🇦', name: 'Ukraine' },
      { char: '🇺🇬', name: 'Uganda' },
      { char: '🇺🇸', name: 'United States' },
      { char: '🇺🇾', name: 'Uruguay' },
      { char: '🇺🇿', name: 'Uzbekistan' },
      { char: '🇻🇦', name: 'Vatican City' },
      { char: '🇻🇨', name: 'St. Vincent & Grenadines' },
      { char: '🇻🇪', name: 'Venezuela' },
      { char: '🇻🇬', name: 'British Virgin Islands' },
      { char: '🇻🇮', name: 'U.S. Virgin Islands' },
      { char: '🇻🇳', name: 'Vietnam' },
      { char: '🇻🇺', name: 'Vanuatu' },
      { char: '🇼🇫', name: 'Wallis & Futuna' },
      { char: '🇼🇸', name: 'Samoa' },
      { char: '🇽🇰', name: 'Kosovo' },
      { char: '🇾🇪', name: 'Yemen' },
      { char: '🇾🇹', name: 'Mayotte' },
      { char: '🇿🇦', name: 'South Africa' },
      { char: '🇿🇲', name: 'Zambia' },
      { char: '🇿🇼', name: 'Zimbabwe' },
    ],
  },
];

const CATEGORY_ICONS: Record<string, IconName> = {
  'People': 'user',
  'Nature': 'tree-pine',
  'Food': 'utensils',
  'Activities': 'gamepad-2',
  'Travel': 'plane',
  'Objects': 'package',
  'Symbols': 'heart',
  'Flags': 'flag',
};

export function EmojiPicker({
  onSelect,
  onClose,
}: {
  onSelect: (emoji: string) => void;
  onClose: () => void;
}) {
  const [activeCategory, setActiveCategory] = useState(0);
  const [searchQuery, setSearchQuery] = useState('');
  const [filteredEmojis, setFilteredEmojis] = useState<{ char: string; name: string }[]>([]);
  const containerRef = useRef<HTMLDivElement>(null);
  const searchInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(e.target as Node)) {
        onClose();
      }
    };
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('keydown', handleKeyDown);
    searchInputRef.current?.focus();
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('keydown', handleKeyDown);
    };
  }, [onClose]);

  useEffect(() => {
    if (searchQuery) {
      const results: { char: string; name: string }[] = [];
      for (const cat of EMOJI_CATEGORIES) {
        for (const emoji of cat.emojis) {
          if (emoji.name.toLowerCase().includes(searchQuery.toLowerCase())) {
            results.push(emoji);
          }
        }
      }
      setFilteredEmojis(results);
    } else {
      setFilteredEmojis([]);
    }
  }, [searchQuery]);

  const category = EMOJI_CATEGORIES[activeCategory];

  return (
    <div
      ref={containerRef}
      className="absolute bottom-full left-4 mb-2 bg-[var(--bg-sidebar)] border border-gray-700 rounded-xl shadow-xl p-3 z-50 max-w-[320px] max-h-[400px] flex flex-col"
      style={{ animation: 'scaleIn 0.15s ease' }}
    >
      {/* Category tabs */}
      <div className="flex gap-0.5 mb-2 overflow-x-auto pb-2 border-b border-gray-700">
        {EMOJI_CATEGORIES.map((cat, i) => (
          <button
            key={cat.name}
            onClick={() => setActiveCategory(i)}
            className={`flex items-center gap-1 px-2 py-1 rounded text-sm transition-colors whitespace-nowrap ${
              i === activeCategory
                ? 'bg-[var(--accent)] text-white'
                : 'text-[var(--text-muted)] hover:text-[var(--text-primary)] hover:bg-[var(--bg-hover)]'
            }`}
          >
            <Icon name={CATEGORY_ICONS[cat.name] || 'smile'} size={14} />
            <span>{cat.name}</span>
          </button>
        ))}
      </div>

      {/* Search */}
      <div className="mb-2">
        <input
          ref={searchInputRef}
          type="text"
          placeholder="Search emojis..."
          value={searchQuery}
          onChange={e => setSearchQuery(e.target.value)}
          className="w-full bg-[#1e1f22] text-[var(--text-primary)] rounded px-3 py-1.5 text-sm outline-none focus:ring-1 focus:ring-[var(--accent)] border border-gray-700"
        />
      </div>

      {/* Emoji grid */}
      <div className="flex-1 overflow-y-auto">
        {searchQuery && filteredEmojis.length === 0 ? (
          <div className="text-center text-[var(--text-muted)] text-sm py-4">No emojis found</div>
        ) : (
          <div className="grid grid-cols-8 gap-1">
            {(searchQuery ? filteredEmojis : category.emojis).map(emoji => (
              <button
                key={emoji.char}
                onClick={() => { onSelect(emoji.char); onClose(); }}
                className="w-8 h-8 flex items-center justify-center text-lg rounded-lg hover:bg-[var(--bg-hover)] transition-colors"
                title={emoji.name}
              >
                {emoji.char}
              </button>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}