-- ════════════════════════════════════════════════════════════════
-- omix-db — D1 (SQLite) schema for Omix Community
-- Replaces the Postgres schema previously hosted on Supabase.
-- Conventions: TEXT ids (UUIDs generated by the worker), TEXT ISO-8601
-- timestamps, TEXT JSON for jsonb-style columns, INTEGER 0/1 for booleans.
-- ════════════════════════════════════════════════════════════════

-- ── Auth ──
CREATE TABLE IF NOT EXISTS users (
  id              TEXT PRIMARY KEY,
  email           TEXT NOT NULL UNIQUE,
  email_confirmed_at TEXT,
  password_hash   TEXT,
  password_salt   TEXT,
  avatar_url      TEXT NOT NULL DEFAULT '',
  full_name       TEXT NOT NULL DEFAULT '',
  bio             TEXT NOT NULL DEFAULT '',
  preferences     TEXT NOT NULL DEFAULT '{}',
  github_username TEXT NOT NULL DEFAULT '',
  last_login      TEXT,
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

CREATE TABLE IF NOT EXISTS sessions (
  token      TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL,
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expires ON sessions(expires_at);

CREATE TABLE IF NOT EXISTS email_tokens (
  token      TEXT PRIMARY KEY,
  user_id    TEXT NOT NULL,
  type       TEXT NOT NULL,                -- 'verify' | 'reset'
  created_at TEXT NOT NULL,
  expires_at TEXT NOT NULL,
  used       INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_email_tokens_user ON email_tokens(user_id);

-- ── Workspaces / servers ──
CREATE TABLE IF NOT EXISTS servers (
  id           TEXT PRIMARY KEY,
  name         TEXT NOT NULL,
  description  TEXT NOT NULL DEFAULT '',
  privacy      TEXT NOT NULL DEFAULT 'private',   -- 'private' | 'public'
  icon         TEXT NOT NULL DEFAULT '',
  member_count INTEGER NOT NULL DEFAULT 1,
  created_by   TEXT NOT NULL,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_servers_privacy ON servers(privacy);

CREATE TABLE IF NOT EXISTS channels (
  id         TEXT PRIMARY KEY,
  server_id  TEXT NOT NULL,
  name       TEXT NOT NULL,
  category   TEXT NOT NULL DEFAULT 'Text Channels',
  type       TEXT NOT NULL DEFAULT 'text',
  topic      TEXT NOT NULL DEFAULT '',
  position   INTEGER NOT NULL DEFAULT 0,
  icon       TEXT NOT NULL DEFAULT '',
  created_by TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_channels_server ON channels(server_id);

CREATE TABLE IF NOT EXISTS server_members (
  id            TEXT PRIMARY KEY,
  server_id     TEXT NOT NULL,
  user_id       TEXT NOT NULL,
  role          TEXT NOT NULL DEFAULT 'member',
  joined_at     TEXT NOT NULL,
  last_read_at  TEXT NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_server_members_unique ON server_members(server_id, user_id);

-- ── Messaging ──
CREATE TABLE IF NOT EXISTS messages (
  id         TEXT PRIMARY KEY,
  channel_id TEXT NOT NULL,
  author     TEXT NOT NULL DEFAULT 'Anonymous',
  author_id  TEXT NOT NULL DEFAULT '',
  session_id TEXT NOT NULL DEFAULT '',
  text       TEXT NOT NULL DEFAULT '',
  color      TEXT NOT NULL DEFAULT '#8B5CF6',
  timestamp  TEXT NOT NULL,
  reactions  TEXT NOT NULL DEFAULT '{}',
  edited     INTEGER NOT NULL DEFAULT 0,
  edited_at  TEXT,
  pinned     INTEGER NOT NULL DEFAULT 0,
  pinned_at  TEXT,
  file_url   TEXT,
  file_type  TEXT,
  file_name  TEXT,
  file_size  INTEGER,
  reply_to   TEXT,
  thread_id  TEXT,
  mentions   TEXT,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_messages_channel ON messages(channel_id, timestamp);
CREATE INDEX IF NOT EXISTS idx_messages_pinned ON messages(channel_id, pinned);
CREATE INDEX IF NOT EXISTS idx_messages_thread ON messages(thread_id);

CREATE TABLE IF NOT EXISTS reactions (
  id         TEXT PRIMARY KEY,
  message_id TEXT NOT NULL,
  user_id    TEXT NOT NULL,
  emoji      TEXT NOT NULL,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_reactions_message ON reactions(message_id);

CREATE TABLE IF NOT EXISTS dm_channels (
  id                   TEXT PRIMARY KEY,
  participants         TEXT NOT NULL DEFAULT '[]',
  participant_names    TEXT NOT NULL DEFAULT '{}',
  last_message_at      TEXT,
  last_message_text    TEXT NOT NULL DEFAULT '',
  last_message_author  TEXT NOT NULL DEFAULT '',
  created_at           TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS dm_messages (
  id            TEXT PRIMARY KEY,
  dm_channel_id TEXT NOT NULL,
  author        TEXT NOT NULL DEFAULT '',
  author_id     TEXT NOT NULL DEFAULT '',
  session_id    TEXT NOT NULL DEFAULT '',
  text          TEXT NOT NULL DEFAULT '',
  color         TEXT NOT NULL DEFAULT '#8B5CF6',
  timestamp     TEXT NOT NULL,
  reactions     TEXT NOT NULL DEFAULT '{}',
  edited        INTEGER NOT NULL DEFAULT 0,
  edited_at     TEXT,
  file_url      TEXT,
  file_type     TEXT,
  file_name     TEXT,
  file_size     INTEGER,
  reply_to      TEXT,
  created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_dm_messages_channel ON dm_messages(dm_channel_id, timestamp);

-- ── Presence / typing / profiles ──
CREATE TABLE IF NOT EXISTS typing (
  id           TEXT PRIMARY KEY,
  channel_id   TEXT NOT NULL,
  user_id      TEXT NOT NULL DEFAULT '',
  display_name TEXT NOT NULL DEFAULT '',
  session_id   TEXT NOT NULL,
  created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_typing_channel ON typing(channel_id);

CREATE TABLE IF NOT EXISTS presence (
  id           TEXT PRIMARY KEY,
  session_id   TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  color        TEXT NOT NULL,
  online       INTEGER NOT NULL DEFAULT 1,
  last_seen    TEXT NOT NULL,
  created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_presence_online ON presence(online);

CREATE TABLE IF NOT EXISTS profiles (
  id              TEXT PRIMARY KEY,
  session_id      TEXT NOT NULL UNIQUE,
  name            TEXT NOT NULL,
  avatar          TEXT NOT NULL DEFAULT '',
  color           TEXT NOT NULL,
  github_username TEXT NOT NULL DEFAULT '',
  bio             TEXT NOT NULL DEFAULT '',
  created_at      TEXT NOT NULL,
  updated_at      TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS stats (
  id                   TEXT PRIMARY KEY,
  session_id           TEXT NOT NULL UNIQUE,
  xp                   INTEGER NOT NULL DEFAULT 0,
  level                INTEGER NOT NULL DEFAULT 1,
  messages_sent        INTEGER NOT NULL DEFAULT 0,
  reactions_received   INTEGER NOT NULL DEFAULT 0,
  replies_received     INTEGER NOT NULL DEFAULT 0,
  badges               TEXT NOT NULL DEFAULT '[]',
  last_message_date    TEXT NOT NULL DEFAULT '',
  streak_count         INTEGER NOT NULL DEFAULT 0,
  join_date            TEXT NOT NULL DEFAULT '',
  created_at           TEXT NOT NULL,
  updated_at           TEXT NOT NULL
);

-- ── Invites / config / notifications ──
CREATE TABLE IF NOT EXISTS invites (
  code       TEXT PRIMARY KEY,
  server_id  TEXT NOT NULL,
  created_by TEXT NOT NULL,
  uses       INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_invites_server ON invites(server_id);

CREATE TABLE IF NOT EXISTS config (
  id         TEXT PRIMARY KEY,
  data       TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS fcm_tokens (
  id           TEXT PRIMARY KEY,
  session_id   TEXT NOT NULL UNIQUE,
  token        TEXT NOT NULL,
  user_id      TEXT NOT NULL DEFAULT '',
  display_name TEXT NOT NULL DEFAULT '',
  updated_at   TEXT NOT NULL,
  created_at   TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS notifications (
  id              TEXT PRIMARY KEY,
  target_user_id  TEXT NOT NULL,
  title           TEXT NOT NULL,
  body            TEXT NOT NULL DEFAULT '',
  data            TEXT NOT NULL DEFAULT '{}',
  sent            INTEGER NOT NULL DEFAULT 0,
  created_at      TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_notifications_target ON notifications(target_user_id);

-- ── Boardroom ──
CREATE TABLE IF NOT EXISTS board_posts (
  id            TEXT PRIMARY KEY,
  title         TEXT NOT NULL,
  body          TEXT NOT NULL,
  category      TEXT NOT NULL DEFAULT 'general',
  author_id     TEXT NOT NULL,
  author_name   TEXT NOT NULL DEFAULT '',
  author_avatar TEXT NOT NULL DEFAULT '',
  author_color  TEXT NOT NULL DEFAULT '#a078ff',
  vote_count    INTEGER NOT NULL DEFAULT 0,
  created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_board_posts_category ON board_posts(category);
CREATE INDEX IF NOT EXISTS idx_board_posts_created ON board_posts(created_at);

CREATE TABLE IF NOT EXISTS board_votes (
  post_id    TEXT NOT NULL,
  session_id TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (post_id, session_id)
);
CREATE INDEX IF NOT EXISTS idx_board_votes_session ON board_votes(session_id);

-- ── Calls ──
CREATE TABLE IF NOT EXISTS call_log (
  id           TEXT PRIMARY KEY,
  caller_id    TEXT NOT NULL,
  callee_id    TEXT NOT NULL,
  caller_name  TEXT NOT NULL DEFAULT '',
  callee_name  TEXT NOT NULL DEFAULT '',
  video        INTEGER NOT NULL DEFAULT 0,
  status       TEXT NOT NULL DEFAULT 'ringing',
  started_at   TEXT NOT NULL,
  ended_at     TEXT,
  duration_ms  INTEGER,
  created_at   TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_call_log_caller ON call_log(caller_id);
CREATE INDEX IF NOT EXISTS idx_call_log_callee ON call_log(callee_id);

-- ── Notification settings ──
CREATE TABLE IF NOT EXISTS notification_settings (
  session_id    TEXT PRIMARY KEY,
  push_enabled  INTEGER NOT NULL DEFAULT 0,
  sound_enabled INTEGER NOT NULL DEFAULT 1,
  message_sound TEXT NOT NULL DEFAULT 'Pop',
  call_ringtone TEXT NOT NULL DEFAULT 'Classic',
  dnd_enabled   INTEGER NOT NULL DEFAULT 0,
  dnd_days      TEXT NOT NULL DEFAULT '[]',
  dnd_start     TEXT NOT NULL DEFAULT '22:00',
  dnd_end       TEXT NOT NULL DEFAULT '08:00',
  updated_at    TEXT NOT NULL
);
